name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        node_version: ['22.x', '24.x']
        os: ['sfdc-hk-ubuntu-latest', 'sfdc-hk-macos-latest', 'sfdc-hk-windows-latest']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - run: npm ci
      - run: npm test
  lint:
    runs-on: sfdc-hk-ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm
      - run: npm ci
      - name: build
        run: npm run build
      - name: linting
        run: npm run lint
